version: '3.7'

services:
  iris:
    build:
      context: ./IRIS
      dockerfile: Dockerfile
    image: isjdctemplate:nativeapi-iris
    init: true
    hostname: nativeapi-iris
    container_name: nativeapi-iris
    ports:
      # webserver/management portal port
      - "52779:52773"
      # superserver default port
      - "1972:1972"
    environment:
      TZ: JST-9

  # docker-compose run java GPXSamples/Sakurajima.gpx.xml
  java:
    build:
      context: ./Java
      dockerfile: Dockerfile
    image: isjdctemplate:nativeapi-java
    init: true
    environment:
      TZ: JST-9
